import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { PluginManager } from './manager.mjs';

const root = await mkdtemp(path.join(tmpdir(), 'aide-plugins-'));
await mkdir(path.join(root, 'demo'));
await writeFile(path.join(root, 'demo', 'aide-plugin.json'), JSON.stringify({ id: 'demo', name: 'Demo', version: '0.1.0', api_version: '1', entry: 'index.mjs', capabilities: ['ui.view'] }));
await writeFile(path.join(root, 'demo', 'index.mjs'), "let d='';process.stdin.on('data', c => d += c);process.stdin.on('end', () => process.stdout.write(JSON.stringify({ok:true, received:JSON.parse(d).ping})));\n");
const probe = "let d='';process.stdin.on('data', c => d += c);process.stdin.on('end', async () => { let reachable=false, code=null; try { await fetch('http://127.0.0.1:59999/'); reachable=true; } catch (e) { let c=e; while (c) { if (c.code) code=c.code; c=c.cause; } code=code||e.message; } process.stdout.write(JSON.stringify({ netAllowed: process.permission.has('net'), reachable, code })); });\n";
await mkdir(path.join(root, 'no-net'));
await writeFile(path.join(root, 'no-net', 'aide-plugin.json'), JSON.stringify({ id: 'no-net', name: 'No Net', version: '1.0.0', api_version: '1', entry: 'index.mjs', capabilities: ['ui.view'] }));
await writeFile(path.join(root, 'no-net', 'index.mjs'), probe);
await mkdir(path.join(root, 'with-net'));
await writeFile(path.join(root, 'with-net', 'aide-plugin.json'), JSON.stringify({ id: 'with-net', name: 'With Net', version: '1.0.0', api_version: '1', entry: 'index.mjs', capabilities: ['ui.view', 'network.localhost'] }));
await writeFile(path.join(root, 'with-net', 'index.mjs'), probe);
const manager = new PluginManager({ pluginsDir: root, statePath: path.join(root, 'state.json') });
assert.equal((await manager.load())[0].trusted, false);
assert.equal((await manager.setTrust('demo', true))[0].enabled, true);
assert.equal((await manager.load())[0].executable, true);
assert.deepEqual(await manager.execute('demo', { ping: 'pong' }), { ok: true, received: 'pong' });

await manager.setTrust('no-net', true);
await manager.setTrust('with-net', true);
const denied = await manager.execute('no-net', {});
assert.equal(denied.netAllowed, false, 'plugin without network.localhost capability must be network-denied');
assert.equal(denied.reachable, false, 'denied plugin must not reach the network');
const granted = await manager.execute('with-net', {});
assert.equal(granted.netAllowed, true, 'plugin with network.localhost capability must receive the network grant');
assert.equal(granted.reachable, false, 'probe endpoint must refuse the connection');
assert.match(String(granted.code), /ECONNREFUSED/, 'granted plugin must actually open a socket');
console.log('plugin manager test passed (trust, execution, network deny-by-default, capability-gated network grant)');